# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  workflow_dispatch:
    inputs:
      releaseType:
        type: choice
        description: Release type
        required: true
        options:
          - release
          - prerelease
          - graduate
      version:
        type: string
        description: Version
      shortDescription:
        type: string
        description: Short description

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps: 
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'corretto'
      - name: Edit version in build.gradle.kts
        run: |
            sed -i "s/version = ".*"/version = \"${{ github.event.inputs.version }}\"/g" build.gradle.kts
      - name: Commit version change
        run: |
          git config --global user.email "rabid-rider-bot@users.noreply.github.com" |
          git config --global user.name "rabid-rider-bot"
          git commit -am "Bump version to ${{ github.event.inputs.version }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      
      - name: Grant execute permission for gradlew
        run: |
            chmod +x gradlew
      - name: Build with Gradle
        run: |
            ./gradlew build
      - name: Create release name
        id: create_relase_name
        run: |
          desc="Release ${{ github.event.inputs.version }}"
          if [ -n "${{ github.event.inputs.shortDescription }}" ]; then
            desc="$desc, ${{ github.event.inputs.shortDescription }}"
          fi
          echo "::set-output name=description::$desc"
      - name: Create New Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.event.inputs.version }}
          release_name: ${{ steps.create_relase_name.outputs.description }}
          draft: false
          artifacts: 'build/libs/*.jar'
          generateReleaseNotes: true
    
      

